snippet = "AATCGCCCAAGACAACATGGGGTTGCAGGTGTAAATCGATAAAAGAAGGGGTAGGTATCGTTCACGGGGCACACTACTAGCGGGGCTTAGATAGCAAACTAGGGGTTCTTCACGCAGCGCAAGACACATGCGCTATAAATGCTAGATCAACTGACATTATACTTATCAATGGGGAATAGGTCAGATAGATGGCACCACCATCGCACACTTATAGGCACGTCACCTGAGCCGACTCGAAATCCGCTTAGTACTGCGACAAAATCATCCGCTCGGTTGATCTAGGATCGGGACTATATCGCAGCGCCCTAGCTCATTCTCACACGTGGAGGGAGCGACGAATGCTCAGCGAGGAGTTGTTCTGACCCGTGACGGAGTACTCTTTACTATCAAGTATAGGCCAGTCTTGCCCCGATCGCTATACATTATTTGATGCCCCCATAGCCGCAGTCATTCGACAGATTAGGCCCACCACCACCTCCCCTTGAGATTGGCTGCATCTACTGTTCAGTCTAATCGCAACTAGCAACATTACGGAAGAAGGGCTACTCTAGATTGTCGCGTACAAGGTTTACCAAAGTGCATAAATCGACGGCCCCTCACGTGCGGCCGTTGGCAAGAGCAACTAAACGCCGGAAGACCCACGCCAATACAGTTCCGCGCCACGGAGGTAACTTACATGCGCGCTCCCCGGTTTACGGGTCATGCCTACCCCTCGGCATTCATGGGACTCAAACCTATCCCCGCAGCCGGAGCTTAAGAAAGAGCTAACACTTAGTTCGCATTCAAAATCGGTAAATTAATTAACATGCCGCAACGCGTCTAGACTACTCCCCGCTTTGCGTTCACCAACGTCCCGAGTTTTAACCTAGAAGCATATGTGCTGACCGTTAGCATACGGTGTTCATCACTCTCGCGATCTCGTCAACTTGGCCATCGCCATCTGGTGGACCCCGGAATCAAAGCTGCTGACTAGAGGCGTTG"
print (snippet)
print("There are "+str(len(snippet))+" characters in it")

countA = 0
countG = 0
countC = 0
countT = 0
for letter in snippet:
    if letter == "A":
        countA += 1
    elif letter == "C":
        countC += 1
    elif letter == "G":
        countG += 1
    elif letter == "T":
        countT += 1
print("There are "+str(countA)+" As")
print("There are "+str(countC)+" Cs")
print("There are "+str(countG)+" Gs")
print("There are "+str(countT)+" Ts")

print("GAT appeats "+str(snippet.count("GAT"))+" times")
rna = snippet.replace("T", "U")
print("RNA is: "+rna)

complement = ""
for letter in snippet:
    if letter == "A":
        complement += "T"
    elif letter == "T":
        complement += "A"
    elif letter == "C":
        complement += "G"
    elif letter == "G":
        complement += "C"
print("The complement is "+complement)
print("The reverse complement is "+complement[::-1])


